steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello World"

substitutions:
  _PR_NUMBER: ''
options:
  logging: CLOUD_LOGGING_ONLY
